### PR TITLE
Use extension task to build native extension

### PR DESCRIPTION
**Pull request by bossmc**
Hey, I know you've abandoned ship on this project, but it's the only globbing library for Ruby so we're still using it (thanks for your work BTW!).  We noticed that your build system for the native part of the gem is quite outdated and this means that tools like `bundler` won't always correctly build the native extension when you install the gem.

This change simply cleans up and modernises the build system to make it work with recent tool-chains.

### CODE REVIEW

**Comment by karottenreibe** [comment]
Thanks for the work :-) I just took a quick glance at the changes, I'm trusting this works :P

**Comment by karottenreibe** [comment]
BTW: feel free to add yourself to some sort of Authors file or similar, if you'd like attribution. Just send me a pull request and I'll merge it :-) If there's a way to make you the repo owner, I'd also be happy to let you take over, if you want (not sure how to do it, though)

**Comment by bossmc** [comment]
Why not?  There's probably not much else I'd change but it's a shame to have a tool die.

I think you need to move the github repository over (under the repository's settings there's a "transfer ownership" option).  It would also be handy if you could transfer ownership of the gem on rubygems.org ("gem owner joker -a andy.m.caldwell@googlemail.com") so I can upload newer versions.

**Comment by karottenreibe** [comment]
Unfortunately, it's telling me "bossmc/joker already exists" :/ But I added you as an owner to the gem. Maybe you just develop on your branch and feel free to push updates to rubygems :-)

**Comment by bossmc** [comment]
Apparently you can't transfer a repository while the target has a fork... seems like that's the only time you'd want to transfer it, but what do I know :grinning:?  I've blown away my fork now, if you want to retry the transfer?

**Pull request merged**
